### ISSUE TITLE
cmake add_pfunit_test expects relative paths

### ISSUE THREAD

**Issue by cmacmackin** [Goddard-Fortran-Ecosystem/pFUnit#122] opened 2019-06-04 09:46 UTC
The `add_pfunit_test` macro in `cmake` only works if it is passed relative paths to the `.pf` files. [Line 101](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/783620d48014a231fed0bffb23a78ec9508f6cbe/cmake/PFUNITConfig.cmake.in#L101) of `PFUNITConfig.cmake` prepends the absolute path to the source directory of CMakeLists.txt to the file name of the pf-source files. This means that if the provided path is already absolute then cmake will look for a nonexistent file. For example, say `CMakeLists.txt` and `test.pf` are both in directory `/a/b/c` and the absolute path to `test.pf` is provided to `add_pfunit_test`. Then cmake will be looking for the test source file at location `/a/b/c/a/b/c/test.pf` where it does not exist.

The solution to this would be to either check whether an absolute path is provided or to compute the relative path using the cmake [`file(RELATIVE_PATH)` command](https://cmake.org/cmake/help/v3.0/command/file.html).

**Comment by tclune** [comment] 2019-06-30 20:02
@cmacmackin   I was having some email issues a few weeks back and apparently missed this issue.    Sorry about that.     I don't see any issues with doing as you request.      Hopefully will do a push this afternoon yet.

**Comment by tclune** [comment] 2019-06-30 20:22
I modified the command to use the SOURCE dir as the working dir, which appears to side-step the entire issue.    I've only done a token test though.   @cmacmackin Could you do a pull from branch feature/#122-allow-absolute-paths-for-tests  and see if this works for you?     I'll then do a merge into develop and roll out a new release with a few other "usability" patches that have accumulated.

**Comment by cmacmackin** [comment] 2019-07-01 14:14
This the problem, but there appears to be a regression which has been introduced at some point while developing v4.0. The paths to the files produced by the preprocessor are now broken. I've attached a reproducer (including the remnants of my attempt at building it in `build/`):

[pfunit-tests-cmake.zip](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/files/3345986/pfunit-tests-cmake.zip)

The output of make is
```
[ 20%] Generating src_gen/tests/simple_tests.F90
Processing file simple_tests.pf
Traceback (most recent call last):
  File "/home/cmacmack/.local/opt/pfunit/pfunit-4.0-beta/PFUNIT-4.0/cmake/../bin/funitproc", line 57, in <module>
    main()
  File "/home/cmacmack/.local/opt/pfunit/pfunit-4.0-beta/PFUNIT-4.0/cmake/../bin/funitproc", line 48, in main
    arguments.f90_filename)
  File "/home/cmacmack/.local/opt/pfunit/pfunit-4.0-beta/PFUNIT-4.0/bin/funit/pFUnitParser.py", line 632, in __init__
    self.outputFile = open(outputFileName, 'w')
IOError: [Errno 2] No such file or directory: '/home/cmacmack/Documents/pfunit-tests-cmake/build/home/cmacmack/Documents/pfunit-tests-cmake/build/src_gen/tests/simple_tests.F90'
CMakeFiles/tests.dir/build.make:61: recipe for target 'src_gen/tests/simple_tests.F90' failed
make[2]: *** [src_gen/tests/simple_tests.F90] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tests.dir/all' failed
make[1]: *** [CMakeFiles/tests.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 
```
The issue is that `CMAKE_CURRENT_BINARY_DIR` is prepended to the path of the output file twice: once on [line 73](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/82d9e26f387119378c6bacf87d108837043c2f30/cmake/PFUNITConfig.cmake.in#L73) of the CMake file (contained within RC_GEN_DIR) and again on [line 101](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/82d9e26f387119378c6bacf87d108837043c2f30/cmake/PFUNITConfig.cmake.in#L101).

**Comment by cmacmackin** [comment] 2019-07-01 14:34
I tried fixing this error in my installation to see if my test would then work. CMake now tried to produce the correct file, but the correct include directories are no longer set due to [line 24](https://github.com/Goddard-Fortran-Ecosystem/pFUnit/blob/82d9e26f387119378c6bacf87d108837043c2f30/cmake/PFUNITConfig.cmake.in#L24) (and those around it) being commented out. In your examples I see that you use a new function `add_pfunit_ctest`, so is `add_pfunit_test` deprecated? I tried using the latter but upon invoking CMake was informed
```
CMake Error at /home/cmacmack/.local/opt/pfunit/pfunit-4.0-beta/PFUNIT-4.0/include/add_pfunit_ctest.cmake:51 (add_executable):
  Target "tests" links to target "OpenMP::OpenMP_Fortran" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:10 (ADD_PFUNIT_CTEST)
```

I had build pFUnit with `-DOPENMP=NO`, so perhaps that is related in some way?

**Comment by tclune** [comment] 2019-07-01 15:15
Apologies for the aggravation, and thanks for the reproducer.    It may be a few days before I can dive into this.

**Comment by tclune** [comment] 2019-07-05 16:36
I modified the last line in CMakeLists.txt in your reproducer.  Before it was:
```cmake
ADD_PFUNIT_TEST(tests "${src_unittest}" "" "")
```
It now reads
```cmake
ADD_PFUNIT_CTEST (tests TEST_SOURCES "${src_unittest}")
```
Note the spelling change  in the macro name and the required keyword.  (Not backward compatible with 3.x)   If you have a lot of instances with the older macro, you should be able to  create your own with the original spelling that wraps the new one.  

With these changes the cmake step proceeds without issue.   The make step still fails due to other changes in 4.0.   In particular,  "use pfunit_mod" should now become "use pfunit" or "use funit" depending on whether MPI is used.   Fixing those, things go a bit further but then I encounter the OpenMP issue you mentioned.

Hopefully I'll get back to you shortly with a fix for the OpenMP issue.   I'm guessing it will require a new release.

**Comment by tclune** [comment] 2019-07-05 16:38
Sorry - my last explanation was a bit confusing.   At first I was testing with the NAG compiler and did not have the OpenMP issue you described.  I then switched to Intel.   The OpenMP issue is at the _cmake_ stage.   The fact that NAG does not have the issue is an important clue.

**Comment by tclune** [comment] 2019-07-05 17:17
OK - if you build pFUnit with -DSKIP_OPENMP=YES, it should resolve the issue for you.   This is another incompatibility with the older version.

Alternatively you can add find_package(OPENMP) in your top level CMakeLists.txt.

I'm going to close this ticket and open another one that is purely about the OpenMP issue.   This was not breaking my demos before when doing a vanilla build and it is now.

If you have further issues along these lines, feel free to reopen the ticket.

**Comment by tclune** [comment] 2019-09-01 21:27
@cmacmackin  When attempting to update a project that was still using pFUnit 3.x,  I finally ran into what might be related issues between relative and absolute paths.   After a bit more thought, I implemented the following.

If the source file is a relative path, it is assumed to be relative to CMAKE_CURRENT_SOURCE_DIR.   If it is an absolute path, it is assumed to be in the build tree.

This new fix works for me for my use cases, but I'm hoping you can try it out when it rolls out to the master branch (probably later this evening).   If this breaks your use case,  I'll contemplate how to insert a switch into the macro to support variant styles.

**Comment by tclune** [comment] 2019-11-10 23:00
@cmacmackin My apologies -doing a bit of cleanup and it looks like the branch with this fix was never merged.    I thought I've even been exercising this functionality, so it is possible that I accidentally included it by some other path.   Investigating ...

**Closed** 2019-11-11 00:28 UTC
