### ISSUE TITLE
@before and @after break compilation

### ISSUE THREAD

**Issue by n-claes** [Goddard-Fortran-Ecosystem/pFUnit#180] opened 2020-01-14 09:39 UTC
I'm running into compilation issues when using the `@before` or `@after` annotations in pFUnit. Everything compiles and runs fine when simply using `@test`, but the error 

`Error: Component 'tree' at (1) is a PRIVATE component of 'stringtestannotationmap'`

gets thrown as soon as I define a subroutine with the `@before` annotation. Strange thing is, the examples from the 'Basic' folder in the `pFUnit_demos` repository **_do_** compile and run fine, and those example tests use the annotations so I'm at a loss here why it doesn't work for my case.

A minimum working example for reproduction is in the 'Trivial' folder of the `pFUnit_demos` repository. Adding the following code snippet to `test_square.pf`

```
@before 
subroutine set_up()
  use funit 

  write(*, *) "ok"
end subroutine set_up
```
throws the above compilation error when running `make`. The example compiles and runs fine without the annotation. Am I missing something trivial here?

I'm running gfortran 9.2.0 on macOS Catalina, using the `master` branch.

**Comment by tclune** [comment] 2020-01-15 16:04
@n-claes Thank you for reporting the issue.    I agree that this should work and the error message likely indicates a compiler bug that may be hard to work around.    This should have been caught by the existing tests.

I may not be able to work on this until the weekend.

**Comment by tclune** [comment] 2020-01-19 00:40
OK - the issue is simply that the constructor for the object that stores the test requires that there be an @after if there is an @before.        I have a vague memory that I once tried to make the arguments optional but ended up fighting with compiler bugs involving overloaded interfaces with optional dummy procedure arguments.

Presumably in the short term you could just have an empty @after procedure.   But I'll attempt a quick fix now, and if it compiles with the relevant compilers will include the extension into the next release.

**Comment by n-claes** [comment] 2020-01-20 12:11
Hi @tclune, great that you could investigate this so quickly! I can confirm that it works if both `@before` and `@after` are used. It actually makes a lot of sense to have them both, for some reason I didn't think of trying to compile it like that... Thank you!

**Comment by tclune** [comment] 2020-01-21 13:27
It would be nice if the error message were a bit less obscure.   (If you know the guts, the message sort of makes sense as the compiler tries to use the default constructor with an opaque data type which does indeed have an opaque data type.)

At any rate the fix is in on the develop branch, so you can use either @before or @after separately if you so desire.    Harder to imagine a case for the latter than for the former.    I may wait for a few more changes to go in before a formal release, but let me know if you need it to be in an actual release sooner than that.

**Comment by n-claes** [comment] 2020-01-22 08:16
Great, I'll check it out! As of right now I've rewritten the tests in such a way that both `@before` and `@after` are actually used. I have the habit of writing a piece of code and then compiling it, which resulted in me implementing only the `@before` subroutine and testing it right after, meaning compilation failed due to the aforementioned issue. It never tried adding `@after` as well before compiling (silly me), hence the confusion as to why it didn't work.

So doing it like that resolved the issue on `master`, and as soon as I need either one of the annotations separately I'll simply checkout `develop` so no need to rush it into an early release ;)
Thanks on following up on this so thoroughly!

**Closed** 2020-04-06 21:00 UTC
